# Generated by Django 5.0.6 on 2024-05-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
        ('cars', '0005_rename_auto_parks_carmodel_auto_park'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoParksModel',
            new_name='AutoParkModel',
        ),
    ]
